name: Issue Notifier

on:
  issues:
    types:
      - opened

jobs:
  issue_tracker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: Notify in Telegram
          run: |
            TgNotify() {
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.CHAT_ID }}" \
              -d parse_mode=Markdown \
              -d text="${1}" \
              -d disable_web_page_preview=true \
              -d message_thread_id="${{ secrets.THREAD_ID }}"
            }
            
            TgNotify "
            #ISSUE\_TRACKER
            *New Issue Opened at* [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Title:* \`${{ github.event.issue.title }}\`
            *User:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *Issue URL:* [Here](${{ github.event.issue.html_url }})"
